#!/bin/sh

set -ex

remote_flags=""
if [[ "$(hostname)" != "space" ]]; then
    remote_flags="--target-host space --use-remote-sudo"
fi

nixos-rebuild \
    $remote_flags \
    -I nixos-config="$(dirname $0)/space/configuration.nix" switch
